import {
  Database,
  Languages,
  Binary,
  Brain,
  FlaskConical,
  PackageOpen,
  SlidersHorizontal,
  ShieldCheck,
  BarChart3,
  Table,
} from "lucide-react";

export const NODE_TYPES = {
  data_preview: {
    type: "data_preview",
    label: "Data Preview",
    description: "View a visual sample of the dataset columns and rows",
    icon: Table,
    color: "hsl(220, 70%, 55%)",
    bgColor: "hsl(220, 60%, 96%)",
    borderColor: "hsl(220, 60%, 82%)",
    inputs: ["data"],
    outputs: ["data"],
    category: "data",
    defaults: {},
  },
  dataset: {
    type: "dataset",
    label: "Dataset",
    description: "Upload or select a training dataset",
    icon: Database,
    color: "hsl(210, 70%, 50%)",
    bgColor: "hsl(210, 60%, 96%)",
    borderColor: "hsl(210, 60%, 82%)",
    inputs: [],
    outputs: ["data"],
    category: "data",
    defaults: {
      datasetId: null,
      format: "csv",
      textColumn: "",
      labelColumn: "",
    },
  },
  preprocessing: {
    type: "preprocessing",
    label: "Preprocessing",
    description: "Clean text, select columns, filter empty rows",
    icon: SlidersHorizontal,
    color: "hsl(250, 55%, 55%)",
    bgColor: "hsl(250, 45%, 96%)",
    borderColor: "hsl(250, 40%, 82%)",
    inputs: ["data"],
    outputs: ["data"],
    category: "data",
    defaults: {
      textColumn: "",
      labelColumn: "",
      lowercase: true,
      stripHtml: true,
      removePunctuation: false,
      removeNumbers: false,
      removeUrls: false,
    },
  },
  language: {
    type: "language",
    label: "Language Expansion",
    description: "Expand dataset into multiple languages using Lingo.dev",
    icon: Languages,
    color: "hsl(280, 60%, 50%)",
    bgColor: "hsl(280, 50%, 96%)",
    borderColor: "hsl(280, 50%, 82%)",
    inputs: ["data"],
    outputs: ["data"],
    category: "data",
    defaults: {
      languages: ["hi", "es", "fr"],
      sourceLanguage: "en",
    },
  },
  validation: {
    type: "validation",
    label: "Validation",
    description: "Check data quality, class balance, and train-readiness",
    icon: ShieldCheck,
    color: "hsl(195, 70%, 42%)",
    bgColor: "hsl(195, 55%, 96%)",
    borderColor: "hsl(195, 50%, 82%)",
    inputs: ["data"],
    outputs: ["data"],
    category: "quality",
    defaults: {
      minRows: 10,
      minClasses: 2,
    },
  },
  embedding: {
    type: "embedding",
    label: "Embedding",
    description: "Generate text embeddings using sentence-transformers",
    icon: Binary,
    color: "hsl(174, 60%, 40%)",
    bgColor: "hsl(174, 50%, 96%)",
    borderColor: "hsl(174, 50%, 82%)",
    inputs: ["data"],
    outputs: ["embeddings"],
    category: "ml",
    defaults: {
      model: "paraphrase-multilingual-MiniLM-L12-v2",
    },
  },
  training: {
    type: "training",
    label: "Training",
    description: "Train ML model using selected algorithm",
    icon: Brain,
    color: "hsl(142, 60%, 38%)",
    bgColor: "hsl(142, 50%, 96%)",
    borderColor: "hsl(142, 45%, 82%)",
    inputs: ["embeddings"],
    outputs: ["model"],
    category: "ml",
    defaults: {
      algorithm: "logistic_regression",
      testSplit: 0.2,
    },
  },
  evaluation: {
    type: "evaluation",
    label: "Evaluation",
    description: "View training metrics: accuracy, precision, recall, F1",
    icon: BarChart3,
    color: "hsl(330, 55%, 50%)",
    bgColor: "hsl(330, 45%, 96%)",
    borderColor: "hsl(330, 40%, 82%)",
    inputs: ["model"],
    outputs: ["model"],
    category: "quality",
    defaults: {},
  },
  testing: {
    type: "testing",
    label: "Testing",
    description: "Test trained model with custom input",
    icon: FlaskConical,
    color: "hsl(38, 80%, 48%)",
    bgColor: "hsl(38, 60%, 96%)",
    borderColor: "hsl(38, 55%, 82%)",
    inputs: ["model"],
    outputs: ["results"],
    category: "output",
    defaults: {
      testInput: "",
    },
  },
  export: {
    type: "export",
    label: "Export",
    description: "Export trained model as package or API",
    icon: PackageOpen,
    color: "hsl(0, 65%, 50%)",
    bgColor: "hsl(0, 50%, 96%)",
    borderColor: "hsl(0, 45%, 85%)",
    inputs: ["model"],
    outputs: [],
    category: "output",
    defaults: {
      format: "python_package",
    },
  },
};

export const NODE_CATEGORIES = {
  data: { label: "Data", order: 1 },
  quality: { label: "Quality", order: 2 },
  ml: { label: "Machine Learning", order: 3 },
  output: { label: "Output", order: 4 },
};

export const ALGORITHMS = [
  { value: "logistic_regression", label: "Logistic Regression" },
  { value: "svm", label: "SVM (Support Vector Machine)" },
  { value: "random_forest", label: "Random Forest" },
  { value: "neural_network", label: "Neural Network (MLP)" },
];

export const SUPPORTED_LANGUAGES = [
  { code: "hi", label: "Hindi" },
  { code: "mr", label: "Marathi" },
  { code: "es", label: "Spanish" },
  { code: "fr", label: "French" },
  { code: "de", label: "German" },
  { code: "pt", label: "Portuguese" },
  { code: "ja", label: "Japanese" },
  { code: "zh", label: "Chinese" },
  { code: "ar", label: "Arabic" },
  { code: "ko", label: "Korean" },
];

export const EXPORT_FORMATS = [
  { value: "python_package", label: "Python Package" },
  { value: "rest_api", label: "REST API" },
  { value: "pickle", label: "Raw Model (.pkl)" },
];

export const EMBEDDING_MODELS = [
  { value: "all-MiniLM-L6-v2", label: "MiniLM-L6 (Fast)" },
  { value: "all-mpnet-base-v2", label: "MPNet Base (Accurate)" },
  { value: "paraphrase-multilingual-MiniLM-L12-v2", label: "Multilingual MiniLM" },
];
